# -*- coding: utf-8 -*-
"""for_while_loops_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMmvx2iqlP1k8wqvZhCC_x03i3jv9SpT
"""

for x in range(6):
 print(x)



for num in range(2, 7): # Iterates from 2 to 6
        print(num)

for n in range(1,9,2):
 print(n)

b=0
while b<=5:
 print(b)
 b=b+1