# -*- coding: utf-8 -*-
"""If_Else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z91YFcuh-DGfEjwG02z-6tjvXFajaKbx
"""

a= int(input())
if(a==4):
  print("number is 4")
else:
  print("number is not 4")
print("Outside")

b= int(input())
if a % 2 ==0:
  print("Even")
else:
  print("odd")

c= int(input())
if c==4:
  print("number is 4")
elif c == 6:
  print('c is 6')
else:
  print("inside")
print("outside")

c= int(input("enter the number"))
if c==4:
  print("number is 4")
elif c==6:
 print("number is 6")
elif c==8:
  print("number is 8")
else:
  print("not valid one")
print("Outside of condition")

d=int(input("enter number"))
if d>4:
  print("number is greater than 4")
  if d<10:
    print("number is greater than 4 and less than 10")