# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2uY5ci2KXq61ZnGN90-GjQUkah_c77c
"""

print(len(input("What is your name")))

username=input("What is your name")
lenth=len(username)
print(lenth)

username="Vijay"
print(username[0])
print(username[-0])

username='Reddy'
print(username[1])
print(username[-1])

username="Arjun"
print(username[:2])
print(username[3:])

username="My name is vijay"
username1="I am Arjun"
print(username[:10])
print(username1[5:])
print(username[:10]+" "+username1[5:])